"use client";
import "./globals.css";
import type { Metadata } from "next";
import Header from "../components/header";
import localFont from "next/font/local";
import SliderMenu from "@/components/slide";
import { Provider } from "react-redux";
import { store } from "@/redux/store";

const yekan = localFont({
  src: [
    {
      path: "./../../public/fonts/iranyekanwebregular.woff2",
      style: "regular",
    },
  ],
  variable: "--yekan-bakh",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl" className={`${yekan.className}`}>
      <Provider store={store}>
        <body className="relative">
          <SliderMenu />
          <Header />
          {children}
        </body>
      </Provider>
    </html>
  );
}
